# Generated by Django 2.1 on 2018-08-23 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ask', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='user',
            new_name='person',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='Title',
            new_name='title',
        ),
    ]
