# Generated by Django 2.1 on 2018-08-24 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ask', '0002_auto_20180824_0015'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='author',
            new_name='person',
        ),
    ]
