# Generated by Django 2.1 on 2018-08-24 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ask', '0004_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='username',
            new_name='user',
        ),
    ]
