# Generated by Django 2.1 on 2018-08-24 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ask', '0005_auto_20180824_2239'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='About',
            new_name='Bio',
        ),
        migrations.AddField(
            model_name='profile',
            name='Education_qualification',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='age',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
