# Generated by Django 2.1 on 2018-08-24 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ask', '0006_auto_20180824_2250'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='question',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='ask.Question'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='Education_qualification',
            field=models.TextField(blank=True, null=True),
        ),
    ]
