# Generated by Django 2.1 on 2018-08-24 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ask', '0007_auto_20180824_2320'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='question',
        ),
    ]
