# Generated by Django 2.1 on 2018-08-24 19:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ask', '0009_profile_question'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='question',
        ),
        migrations.AddField(
            model_name='question',
            name='profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='profile', to='ask.Profile'),
            preserve_default=False,
        ),
    ]
