# Generated by Django 2.1 on 2018-08-26 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ask', '0011_auto_20180825_0135'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='img/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='img/'),
        ),
    ]
